import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import appleGothic from "@/utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script src="https://kit.fontawesome.com/48e58babbf.js" />
      <body className={appleGothic.className}>{children}</body>
    </html>
  );
}
