import type { Metadata } from "next";
import "../globals.css";
import Script from "next/script";
import appleGothic from "@/utils/font";
import { Toaster } from "react-hot-toast";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: {
    locale: "en";
  };
}) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <Script src="https://kit.fontawesome.com/48e58babbf.js" />
      <body className={appleGothic.className}>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <Toaster
            position="bottom-center"
            containerStyle={{
              inset: "16px 16px 60px 16px",
            }}
          />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
