import type { Metadata } from "next";
import "../globals.css";
import appleGothic from "@/utils/font";
import { Toaster } from "react-hot-toast";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { ReactNode } from "react";
import { LOCALES } from "@/utils/navigation";
import EventHandler from "@/components/EventHandler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: {
    locale: (typeof LOCALES)[number];
  };
}) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={appleGothic.className}>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <Toaster
            position="bottom-center"
            containerStyle={{
              inset: "16px 16px 60px 16px",
            }}
          />
          <EventHandler />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
